from __future__ import annotations

import argparse
import csv
from pathlib import Path

from scrape_features.group_posts.scraper import clean_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create a comment plan CSV from scraped group post bodies. "
            "The output can be reviewed and then used by the comment executor."
        )
    )
    parser.add_argument(
        "--input",
        default="scrape_features/post_bodies/data/group_post_bodies.csv",
        help="Input CSV generated by post-bodies scraper.",
    )
    parser.add_argument(
        "--output",
        default="scrape_features/comment_replies/data/comment_plan.csv",
        help="Output CSV containing generated comment ideas per post.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Optional maximum number of rows to process (0 = all).",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output file if it already exists.",
    )
    return parser.parse_args()


def build_comment_idea(content: str) -> str:
    text = clean_text(content)
    lower = text.lower()

    if "mất gốc" in lower or "moi bat dau" in lower or "mới bắt đầu" in lower:
        return (
            "Nếu mới bắt đầu thì bạn có thể chia nhỏ mục tiêu theo tuần, "
            "ưu tiên luyện đều speaking + listening trước để tăng nền nhanh."
        )
    if "target" in lower or "điểm" in lower:
        return (
            "Bạn chia sẻ mục tiêu rất rõ rồi, mình nghĩ nên tập trung 1-2 kỹ năng yếu nhất "
            "và test mock định kỳ để đo tiến bộ."
        )
    if "tips" in lower or "kinh nghiệm" in lower:
        return (
            "Cảm ơn bạn đã mở chủ đề hay, bạn có thể thử ghi lại lỗi sai lặp lại sau mỗi lần luyện "
            "để cải thiện nhanh hơn."
        )
    if "share tài khoản" in lower or "pass tài khoản" in lower:
        return "Bạn nên xác minh thông tin kỹ trước khi giao dịch để tránh rủi ro nhé."
    if "thi" in lower and "pte" in lower:
        return (
            "Chúc bạn thi tốt, nhớ luyện theo điều kiện thời gian thật và ưu tiên những dạng câu "
            "bạn thường sai trong mock."
        )

    return (
        "Cảm ơn bạn đã chia sẻ. Mình nghĩ bạn nên giữ lịch luyện đều mỗi ngày và theo dõi "
        "tiến độ theo từng kỹ năng để tối ưu thời gian."
    )


def make_excerpt(content: str, max_chars: int = 140) -> str:
    text = clean_text(content)
    if len(text) <= max_chars:
        return text
    return f"{text[: max_chars - 1].rstrip()}…"


def read_post_rows(input_path: Path) -> list[dict[str, str]]:
    with input_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        return list(csv.DictReader(csv_file))


def write_plan_rows(output_path: Path, rows: list[dict[str, str]]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "post_key",
        "post_url",
        "author",
        "content_excerpt",
        "generated_comment",
        "status",
        "error",
    ]
    with output_path.open("w", encoding="utf-8-sig", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def generate_plan(
    input_path: Path,
    output_path: Path,
    *,
    limit: int = 0,
    overwrite: bool = False,
) -> int:
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")
    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"Output file already exists: {output_path}. Use --overwrite to replace it."
        )

    posts = read_post_rows(input_path)
    if limit > 0:
        posts = posts[:limit]

    plan_rows: list[dict[str, str]] = []
    for post in posts:
        content = post.get("content", "")
        plan_rows.append(
            {
                "post_key": post.get("post_key", ""),
                "post_url": post.get("post_url", ""),
                "author": post.get("author", ""),
                "content_excerpt": make_excerpt(content),
                "generated_comment": build_comment_idea(content),
                "status": "pending",
                "error": "",
            }
        )

    write_plan_rows(output_path, plan_rows)
    return len(plan_rows)


def main() -> None:
    args = parse_args()
    count = generate_plan(
        Path(args.input).resolve(),
        Path(args.output).resolve(),
        limit=args.limit,
        overwrite=args.overwrite,
    )
    print(f"Generated {count} comment ideas.")
    print(f"Saved plan to {Path(args.output).resolve()}")


if __name__ == "__main__":
    main()
